package com.todo.service.impl;

import com.todo.entity.Task;
import com.todo.repository.TaskRepository;
import com.todo.service.TaskService;
import com.todo.util.PaginationUtils;
import jakarta.transaction.Transactional;
import lombok.RequiredArgsConstructor;
import org.springframework.data.domain.Page;
import org.springframework.http.HttpStatus;
import org.springframework.stereotype.Service;
import org.springframework.web.server.ResponseStatusException;

import java.time.Instant;
import java.util.List;
import java.util.UUID;

@Service
@RequiredArgsConstructor
@Transactional
public class TaskServiceImpl implements TaskService {

    private final TaskRepository repo;

    @Override
    public List<Task> listTasks() {
        return repo.findAllByDeletedFalseOrderByCreatedAtDesc();
    }

    // paginated tasks
    @Override
    public Page<Task> listTasks(int page, int size, String sort) {
        return repo.findAllByDeletedFalse(PaginationUtils.buildPageable(page, size, sort));
    }

    @Override
    public List<Task> listAllTasks() {
        return repo.findAllByDeletedFalseOrderByCreatedAtDesc();
    }

    @Override
    public Page<Task> listAllTasks(int page, int size, String sort) {
        return repo.findAll(PaginationUtils.buildPageable(page, size, sort));
    }

    @Override
    public Task getTaskById(UUID id) {
        return repo.findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Task not found"));
    }

    @Override
    @Transactional
    public Task createTask(String taskName, String taskDesc) {
        Task t = Task.builder()
                .taskName(taskName)
                .taskDesc(taskDesc)
                .createdAt(Instant.now())
                .completed(false)
                .deleted(false)
                .build();
        return repo.save(t);
    }

    @Override
    @Transactional
    public Task updateTask(UUID id, String taskName, String taskDesc, Boolean completed) {
        Task t = getTaskById(id);
        if (taskName != null) t.setTaskName(taskName);
        if (taskDesc != null) t.setTaskDesc(taskDesc);
        if (completed != null) t.setCompleted(completed);
        return repo.save(t);
    }

    @Override
    @Transactional
    public void deleteTask(UUID id) {
        Task t = repo.findById(id)
                .orElseThrow(() -> new ResponseStatusException(HttpStatus.NOT_FOUND, "Task not found"));
        if (!t.isDeleted()) {
            t.setDeleted(true);
            repo.save(t);
        }
    }

    @Override
    @Transactional
    public Task setCompleted(UUID id, Boolean completed) {
        Task t = getTaskById(id);
        t.setCompleted(completed);
        return repo.save(t);
    }

    @Override
    @Transactional
    public Task insertMock() {
        return createTask("Mock Task", "Generated by /tasks/mock");
    }
}
